name: Build & Publish

on: [ workflow_dispatch, push ]
    # branches: [ "main" ]

jobs:
  version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version-output.outputs.version-tag }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Version
        if: ${{ github.ref_type != 'branch' }}
        id: version
        uses: PaulHatch/semantic-version@v5.0.3
        with:
          version_format: "v${major}.${minor}.${patch}"
          major_pattern: "MAJOR"
          minor_pattern: "MINOR"
          # bump_each_commit: true
      - name: Version (Dev)
        if: ${{ github.ref_type == 'branch' }}
        id: version-dev
        uses: PaulHatch/semantic-version@v5.0.3
        with:
          version_format: "v${major}.${minor}.${patch}-${{ github.ref_name }}"
          major_pattern: "MAJOR"
          minor_pattern: "MINOR"
          # bump_each_commit: true
      - name: Version Output
        id: version-output
        shell: bash
        run: |
          if [[ ${{ github.ref_type == 'branch' }} ]]; then GIT_TAG="${{ steps.version-dev.outputs.version }}"
          else GIT_TAG="${{ steps.version-dev.outputs.version }}"
          fi
          echo "version-tag=${GIT_TAG}" >> "$GITHUB_OUTPUT"

      - name: Tag Version
        if: ${{ github.ref_type != 'branch' }}
        id: tag
        shell: bash
        run: |
          echo "Semantic version: ${{ steps.version-output.outputs.version }}"
          git tag ${{ steps.version.outputs.version }}
          git push origin --tags

  build-and-push:
    needs: [ version ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: bossanova456
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build image and push (arm64)
        uses: docker/build-push-action@v4
        with:
          push: true
          platforms: linux/arm64
          tags: |
            bossanova456/chandler-cup-frontend:latest-arm64
            bossanova456/chandler-cup-frontend:${{ needs.version.outputs.version }}-arm64
