name: Manual Docker Build & Push

on: workflow_dispatch

jobs:
  version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Version
        id: version
        uses: PaulHatch/semantic-version@v5.0.3
        with:
          version_format: "v${major}.${minor}.${patch}-${{ github.ref_name }}-${increment}"
          major_pattern: "MAJOR"
          minor_pattern: "MINOR"

  build-image-and-push:
    needs: [ version ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: bossanova456
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build image and push (arm64)
        uses: docker/build-push-action@v4
        with:
          push: true
          platforms: linux/arm64
          tags: bossanova456/chandler-cup-frontend:${{ needs.version.outputs.version }}-arm64